site_name: Creative Writing 10
site_description: Readings and syllabus for class

plugins:
  - search
  - awesome-pages

theme:
  name: material
  custom_dir: overrides
  font:
    text: "Source Serif 4"
    code: "Roboto Mono"
  icon:
    logo: material/cat
    favicon: material/cat
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - search.suggest

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

markdown_extensions:
  - attr_list
  - admonition

extra_javascript:
  - javascripts/password-protect.js

validation:
  links:
    absolute_links: relative_path
