site_name: Creative Writing 10
site_description: Readings and syllabus for class

plugins:
  - search
  - reading-time:                           # <--- UPDATED PLUGIN NAME
      words_per_minute: 200

theme:
  name: material
  font:
    text: "Source Serif 4"
    code: "Roboto Mono"
  icon:
    logo: material/cat
    favicon: material/cat
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - search.suggest

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Syllabus:
      - Course Info: intro.md
      - Sample: index.md
