site_name: Creative Writing 10
site_description: Readings and syllabus for class

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.sections
    - search.suggest

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Syllabus:
      - Course Info: intro.md

