name: ci 
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # Install both material and the official Dracula theme package:
      - run: pip install mkdocs-material mkdocs-dracula-theme
      - run: mkdocs gh-deploy --force
